name: "github test run for echo"
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: echo "hello"
      - name: run multiple commandds
        run: |
          echo "line1"
          echo "line2"
